// generated by claude

// clang -o capslock capslock.c \
//   -framework IOKit \
//   -framework CoreFoundation \
//   -framework Carbon



#include <stdio.h>
#include <IOKit/hid/IOHIDLib.h>
#include <mach/mach_time.h>

static IOHIDDeviceRef find_keyboard() {
    IOHIDManagerRef mgr = IOHIDManagerCreate(kCFAllocatorDefault, kIOHIDOptionsTypeNone);

    CFDictionaryRef filter = CFDictionaryCreate(
        kCFAllocatorDefault,
        (const void *[]){ CFSTR(kIOHIDDeviceUsagePageKey), CFSTR(kIOHIDDeviceUsageKey) },
        (const void *[]){
            CFNumberCreate(kCFAllocatorDefault, kCFNumberIntType, &(int){ kHIDPage_GenericDesktop }),
            CFNumberCreate(kCFAllocatorDefault, kCFNumberIntType, &(int){ kHIDUsage_GD_Keyboard })
        },
        2, &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks
    );

    IOHIDManagerSetDeviceMatching(mgr, filter);
    IOHIDManagerOpen(mgr, kIOHIDOptionsTypeNone);

    CFSetRef devices = IOHIDManagerCopyDevices(mgr);
    if (!devices) return NULL;

    CFIndex count = CFSetGetCount(devices);
    IOHIDDeviceRef *devs = calloc(count, sizeof(IOHIDDeviceRef));
    CFSetGetValues(devices, (const void **)devs);

    IOHIDDeviceRef result = NULL;
    for (CFIndex i = 0; i < count; i++) {
        CFStringRef name = IOHIDDeviceGetProperty(devs[i], CFSTR(kIOHIDProductKey));
        if (name && CFStringFind(name, CFSTR("Karabiner DriverKit VirtualHIDKeyboard"), 0).location != kCFNotFound) {
            result = devs[i];
            break;
        }
    }

    free(devs);
    return result;
}
// Get current CapsLock LED state
static int get_capslock(IOHIDDeviceRef keyboard) {
    CFArrayRef elements = IOHIDDeviceCopyMatchingElements(
        keyboard, NULL, kIOHIDOptionsTypeNone
    );
    
    for (CFIndex i = 0; i < CFArrayGetCount(elements); i++) {
        IOHIDElementRef elem = (IOHIDElementRef)CFArrayGetValueAtIndex(elements, i);
        if (IOHIDElementGetUsagePage(elem) == kHIDPage_LEDs &&
            IOHIDElementGetUsage(elem) == kHIDUsage_LED_CapsLock) {
            
            IOHIDValueRef val;
            if (IOHIDDeviceGetValue(keyboard, elem, &val) == kIOReturnSuccess) {
                return (int)IOHIDValueGetIntegerValue(val);
            }
        }
    }
    return -1;
}

// Set CapsLock LED state (1 = on, 0 = off)
static void set_capslock(IOHIDDeviceRef keyboard, int state) {
    CFArrayRef elements = IOHIDDeviceCopyMatchingElements(
        keyboard, NULL, kIOHIDOptionsTypeNone
    );
    
    for (CFIndex i = 0; i < CFArrayGetCount(elements); i++) {
        IOHIDElementRef elem = (IOHIDElementRef)CFArrayGetValueAtIndex(elements, i);
        if (IOHIDElementGetUsagePage(elem) == kHIDPage_LEDs &&
            IOHIDElementGetUsage(elem) == kHIDUsage_LED_CapsLock) {
            
            IOHIDValueRef val = IOHIDValueCreateWithIntegerValue(
                kCFAllocatorDefault, elem, mach_absolute_time(), state
            );
            IOHIDDeviceSetValue(keyboard, elem, val);
            CFRelease(val);
            return;
        }
    }
}

int main(int argc, char *argv[]) {
    IOHIDDeviceRef keyboard = find_keyboard();
    if (!keyboard) {
        fprintf(stderr, "No keyboard found\n");
        return 1;
    }

    // IOHIDDeviceOpen(keyboard, kIOHIDOptionsTypeNone);
    // IOHIDDeviceScheduleWithRunLoop(keyboard, CFRunLoopGetCurrent(), kCFRunLoopDefaultMode);
    // CFRunLoopRunInMode(kCFRunLoopDefaultMode, 0.1, false);


    if (argc == 1) {
        // No args: read state
        int state = get_capslock(keyboard);
        printf("CapsLock: %s\n", state == 1 ? "ON" : state == 0 ? "OFF" : "unknown");
    } else if (argc == 2) {
        // Arg: set state
        int state = atoi(argv[1]);
        set_capslock(keyboard, state);
        printf("CapsLock LED set to %s\n", state ? "ON" : "OFF");
    }

    return 0;
}